name: Sync Google Doc on docs changes

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  ping-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Apps Script webhook (instant Doc sync)
        env:
          SYNC_URL: ${{ secrets.APPS_SCRIPT_SYNC_URL }}
          SYNC_TOKEN: ${{ secrets.APPS_SCRIPT_TOKEN }}
        run: |
          if [ -z "$SYNC_URL" ] || [ -z "$SYNC_TOKEN" ]; then
            echo 'APPS_SCRIPT_SYNC_URL or APPS_SCRIPT_TOKEN is not set as a repo secret';
            exit 1;
          fi
          curl -sS -X POST "$SYNC_URL" \
            -H 'Content-Type: application/json' \
            -d "{\"token\":\"$SYNC_TOKEN\",\"repo\":\"${{ github.repository }}\",\"sha\":\"${{ github.sha }}\"}"
